server:
  servlet:
    context-path: /
  port: ${APP_PORT:8901}
 
spring:
  application:
    name: ${APP_NAME:apoiador-requisitante}
    version: 0.0.1
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: ${RABBIT_VHOST:/}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    connection-timeout: 1000ms
    listener:
      direct:
        prefetch: ${RABBIT_PREFETCH:25}
      simple:
        prefetch: ${RABBIT_PREFETCH:20}
        concurrency: ${RABBIT_CONCURRENCY:3}
        max-concurrency: ${RABBIT_MAX_CONCURRENCY:10}
    template:
      default-receive-queue: ${RABBIT_JIRA01_APOIADOR_REQUISITANTE_QUEUE:jira010-apoiador-requisitante.queue}
      exchange: ${RABBIT_EXCHANGE:dev-platform.exchange}
      custom:
        # TODO - migrar esta queue para um novo servico separado deste daqui - pre-requisito: o clientejira deve estar separado em um servico fora deste aqui
        jira020-classification-queue: 
          name: ${RABBIT_JIRA02_SUPEREPICTHEME_QUEUE:jira020-super-epic-theme.queue}
          auto-startup: ${RABBIT_JIRA02_SUPEREPICTHEME_QUEUE_AUTOSTARTUP:false}
        jira030-resposta-demandante:
          name: ${RABBIT_JIRA03_RESPOSTA_DEMANDANTE_QUEUE:jira030-resposta-demandante.queue}
          auto-startup: ${RABBIT_JIRA03_RESPOSTA_DEMANDANTE_QUEUE_AUTOSTARTUP:false}
        jira040-raia-fluxo:
          name: ${RABBIT_JIRA04_RAIA_FLUXO_QUEUE:jira040-raia-fluxo.queue}
          auto-startup: ${RABBIT_JIRA04_RAIA_FLUXO_AUTOSTARTUP:false}

        gitlab010-commit-script-queue:
          name: ${RABBIT_GITLAB010_COMMIT_SCRIPT_QUEUE:gitlab010-commit-script.queue}
          auto-startup: ${RABBIT_GITLAB010_COMMIT_SCRIPT_AUTOSTARTUP:false}
        gitlab020-gitflow-queue:
          name: ${RABBIT_GITLAB020_GITFLOW_QUEUE:gitlab020-gitflow-queue}
          auto-startup: ${RABBIT_GITLAB020_GITFLOW_AUTOSTARTUP:false}
        gitlab030-merge-request-merge-close:
          name: ${RABBIT_GITLAB030_MERGE_REQUEST_MERGE_CLOSE_QUEUE:gitlab030-merge-request-merge-close-queue}
          auto-startup: ${RABBIT_GITLAB030_MERGE_REQUEST_MERGE_CLOSE_AUTOSTARTUP:false}
        gitlab040-tag-pushed-end-version:
          name: ${RABBIT_GITLAB040_TAG_PUSHED_END_VERSION_QUEUE:gitlab040-tag-pushed-end-version-queue}
          auto-startup: ${RABBIT_GITLAB040_TAG_PUSHED_END_VERSION_AUTOSTARTUP:false}
        gitlab050-tag-pushed-prepare-next-version:
          name: ${RABBIT_GITLAB050_TAG_PUSHED_PREPARE_NEXT_VERSION_QUEUE:gitlab050-tag-pushed-prepare-next-version-queue}
          auto-startup: ${RABBIT_GITLAB050_TAG_PUSHED_PREPARE_NEXT_VERSION_AUTOSTARTUP:false}
        gitlab060-merge-request-approvals:
          name: ${RABBIT_GITLAB060_MERGE_REQUEST_APPROVALS_QUEUE:gitlab060-merge-request-approvals-queue}
          auto-startup: ${RABBIT_GITLAB060_MERGE_REQUEST_APPROVALS_AUTOSTARTUP:false}
          
          
        lanver010-triage-queue:
          name: ${RABBIT_LANVER010_TRIAGE_QUEUE:lanver010-triage-queue}
          auto-startup: ${RABBIT_LANVER010_TRIAGE_QUEUE_AUTOSTARTUP:false}
          routing-key-created: ${RABBIT_LANVER010_TRIAGE_JIRA_ISSUE_CREATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_CREATED.*.10200.1.#}
          routing-key-updated: ${RABBIT_LANVER010_TRIAGE_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.1.#}
        lanver015-prepare-actual-version-queue:
          name: ${RABBIT_LANVER015_PREPARE_ACTUAL_VERSION_QUEUE:lanver015-prepare-actual-version-queue}
          auto-startup: ${RABBIT_LANVER015_PREPARE_ACTUAL_VERSION_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER015_PREPARE_ACTUAL_VERSION_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10677.#}
        lanver020-release-candidate-queue:
          name: ${RABBIT_LANVER020_CREATE_RELEASE_CANDIDATE_QUEUE:lanver020-release-candidate-queue}
          auto-startup: ${RABBIT_LANVER020_CREATE_RELEASE_CANDIDATE_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER020_CREATE_RELEASE_CANDIDATE_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10671.#}
        lanver030-next-version-queue:
          name: ${RABBIT_LANVER030_PREPARE_NEXT_VERSION_QUEUE:lanver030-prepare-next-version-queue}
          auto-startup: ${RABBIT_LANVER030_PREPARE_NEXT_VERSION_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER030_PREPARE_NEXT_VERSION_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10672.#}
        lanver040-release-notes-queue:
          name: ${RABBIT_LANVER040_CREATE_RELEASE_NOTES_QUEUE:lanver040-release-notes-queue}
          auto-startup: ${RABBIT_LANVER040_CREATE_RELEASE_NOTES_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER040_CREATE_RELEASE_NOTES_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10670.#}
        lanver050-version-launch-queue:
          name: ${RABBIT_LANVER050_PROCESS_RELEASE_NOTES_QUEUE:lanver050-version-launch-queue}
          auto-startup: ${RABBIT_LANVER050_PROCESS_RELEASE_NOTES_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER050_PROCESS_RELEASE_NOTES_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10572.#}
        lanver060-publish-release-notes-queue:
          name: ${RABBIT_LANVER060_PUBLISH_RELEASE_NOTES_QUEUE:lanver060-publish-release-notes-queue}
          auto-startup: ${RABBIT_LANVER060_PUBLISH_RELEASE_NOTES_QUEUE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_LANVER060_PUBLISH_RELEASE_NOTES_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.10200.10673.#}
        lanver070-tag-pushed-queue:
          name: ${RABBIT_LANVER070_TAG_PUSHED_QUEUE:lanver070-tag-pushed-queue}
          auto-startup: ${RABBIT_LANVER070_PUBLISH_TAG_PUSHED_QUEUE_AUTOSTARTUP:false}

        documentation01-triage-queue:
          name: ${RABBIT_DOCUMENTATION01_TRIAGE_QUEUE:documentation01-triage-queue}
          auto-startup: ${RABBIT_DOCUMENTATION01_TRIAGE_AUTOSTARTUP:false}
          routing-key-created: ${RABBIT_DOCUMENTATION01_TRIAGE_JIRA_ISSUE_CREATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_CREATED.*.*.1.PJEDOC.#}
          routing-key-updated: ${RABBIT_DOCUMENTATION01_TRIAGE_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.*.1.PJEDOC.#}
        documentation02-create-solution-queue:
          name: ${RABBIT_DOCUMENTATION02_CREATE_SOLUTION_QUEUE:documentation02-create-solution-queue}
          auto-startup: ${RABBIT_DOCUMENTATION02_CREATE_SOLUTION_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_DOCUMENTATION02_CREATE_SOLUTION_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.*.10674.PJEDOC.#}
        documentation03-check-automatic-merge:
          name: ${RABBIT_DOCUMENTATION03_CHECK_AUTOMATIC_MERGE_QUEUE:documentation03-check-automatic-merge-queue}
          auto-startup: ${RABBIT_DOCUMENTATION03_CHECK_AUTOMATIC_MERGE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_DOCUMENTATION03_CHECK_AUTOMATIC_MERGE_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.*.10480.PJEDOC.#}
        documentation04-manual-merge:
          name: ${RABBIT_DOCUMENTATION04_MANUAL_MERGE_QUEUE:documentation04-manual-merge-queue}
          auto-startup: ${RABBIT_DOCUMENTATION04_MANUAL_MERGE_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_DOCUMENTATION04_MANUAL_MERGE_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.*.10043.PJEDOC.#}
        documentation05-finish-homologation:
          name: ${RABBIT_DOCUMENTATION05_FINISH_HOMOLOGATION_QUEUE:documentation05-finish-homologation-queue}
          auto-startup: ${RABBIT_DOCUMENTATION05_FINISH_HOMOLOGATION_AUTOSTARTUP:false}
          routing-key-updated: ${RABBIT_DOCUMENTATION05_FINISH_HOMOLOGATION_JIRA_ISSUE_UPDATED_ROUTINGKEY_PREFIX:dev-platform.jira.ISSUE_UPDATED.*.*.10054.PJEDOC.#}
          
        gamification010-classificar-areas-conhecimento:
          name: ${RABBIT_GAMIFICATION010_CLASSIFICAR_AREAS_CONHECIMENTO_QUEUE:gamification010-classificar-areas-conhecimento-queue}
          auto-startup: ${RABBIT_GAMIFICATION010_CLASSIFICAR_AREAS_CONHECIMENTO_AUTOSTARTUP:false}
          routing-key-start: ${RABBIT_GAMIFICATION010_CLASSIFICAR_AREAS_CONHECIMENTO_ROUTING_KEY_START:dev-platform.gamification.areas-conhecimento-classificar}
          routing-key-end: ${RABBIT_GAMIFICATION010_CLASSIFICAR_AREAS_CONHECIMENTO_ROUTING_KEY_END:dev-platform.gamification.areas-conhecimento-classificadas}
          
        gamification020-calculo-prioridade-demanda:
          name: ${RABBIT_GAMIFICATION020_CALCULO_PRIORIDADE_DEMANDA_QUEUE:gamification020-calculo-prioridade-demanda-queue}
          auto-startup: ${RABBIT_GAMIFICATION020_CALCULO_PRIORIDADE_DEMANDA_AUTOSTARTUP:false}
          
        jira:
          issue-created:
            routing-key: ${RABBIT_JIRA_ISSUE_CREATED_ROUTINGKEY:dev-platform.jira.ISSUE_CREATED.#}
          issue-updated:
            routing-key: ${RABBIT_JIRA_ISSUE_UPDATED_ROUTINGKEY:dev-platform.jira.ISSUE_UPDATED.#}
          issue-commented:
            routing-key: ${RABBIT_JIRA_ISSUE_COMMENTED_ROUTINGKEY:dev-platform.jira.ISSUE_COMMENTED.#}
          issue-comment-edited:
            routing-key: ${RABBIT_JIRA_ISSUE_COMMENT_EDITED_ROUTINGKEY:dev-platform.jira.ISSUE_COMMENT_EDITED.#}
          issue-generic:
            routing-key: ${RABBIT_JIRA_ISSUE_GENERIC_ROUTINGKEY:dev-platform.jira.ISSUE_GENERIC.#}

        gitlab:
          push:
            routing-key: ${RABBIT_GITLAB_PUSH_ROUTINGKEY:dev-platform.gitlab.PUSH}
          tag-push:
            routing-key: ${RABBIT_GITLAB_TAGPUSH_ROUTINGKEY:dev-platform.gitlab.TAG_PUSH}
          merge-request:
            routing-key: ${RABBIT_GITLAB_MERGE_REQUEST_ROUTINGKEY:dev-platform.gitlab.MERGE_REQUEST}
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

clients:
  jira:
    url: ${SERVICE_JIRA_URL:my-jira-url}
    user: ${SERVICE_JIRA_USER:my-user}
    pass: ${SERVICE_JIRA_PASSWORD:my-pass}
  slack:
    url: https://slack.com/api/
    token: ${SERVICE_SLACK_TOKEN:my-slack-bot-token}
  gitlab:
    url: ${SERVICE_GITLAB_URL:my-gitlab-url}
    token: ${SERVICE_GITLAB_TOKEN:my-gitlab-token}
  telegram:
    url: https://api.telegram.org/
    token: ${SERVICE_TELEGRAM_TOKEN:my-telegram-bot-token}
  rocketchat:
    url: ${SERVICE_ROCKETCHAT_URL:my-roccket-url}
    userid: ${SERVICE_ROCKETCHAT_USERID:my-user-id}
    token: ${SERVICE_ROCKETCHAT_TOKEN:my-token}

project:
  documentation:
    url: ${PROJECT_DOCUMENTATION_URL:my-documentation-url}
    manual-revisao-codigo: ${PROJECT_DOCUMENTATION_MANUAL_REVISAO_CODIGO:my-documentation-revisao-codigo-url}
  jira.filters:
    pendentes-geral: ${JIRA_FILTERS_ISSUES_PENDENTES_GERAL:0}
  telegram.channel:
    name: ${PROJECT_TELEGRAM_CHANNEL_NAME:my-telegram-channel-name}
    url: ${PROJECT_TELEGRAM_CHANNEL_URL:my-telegram-channel-url}
    triage-bot-id: ${PROJECT_TELEGRAM_CHANNEL_BOT_TRIAGEM:my-telegram-triage-bot-channel-id}
    geral: ${PROJECT_TELEGRAM_CHANNEL_GENERAL:my-telegram-general-channel-id}
  rocketchat:
    channel:
      triage-bot-id: ${PROJECT_ROCKETCHAT_CHANNEL_BOT_TRIAGEM:my-triage-bot-channel}
      grupo-revisor-id: ${PROJECT_ROCKETCHAT_CHANNEL_GRUPO_REVISOR:my-grupo-revisor-channel}
      grupo-negocial-id: ${PROJECT_ROCKETCHAT_CHANNEL_GRUPO_NEOGIAL:my-grupo-neogical-channel}
      pje-news-id: ${PROJECT_ROCKETCHAT_CHANNEL_PJENEWS:my-pjenews-channel}
      pje-dev-platform-id: ${PROJECT_ROCKETCHAT_CHANNEL_PJEDEVPLATFORM:my-pjedevplatform-channel}
      geral: ${PROJECT_ROCKETCHAT_CHANNEL_GENERAL:general}
  slack:
    channel:
      triage-bot-id: ${PROJECT_SLACK_CHANNEL_BOT_TRIAGEM:my-triage-bot-channel}
      grupo-revisor-id: ${PROJECT_SLACK_CHANNEL_GRUPO_REVISOR:my-grupo-revisor-channel}
      grupo-negocial-id: ${PROJECT_SLACK_CHANNEL_GRUPO_NEOGIAL:my-grupo-neogical-channel}
      pje-news-id: ${PROJECT_SLACK_CHANNEL_PJENEWS:my-pjenews-channel}
      geral: ${PROJECT_SLACK_CHANNEL_GENERAL:general}